[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

# Specify environment variables for TypeScript support
[build.environment]
  NODE_VERSION = "14"  # Specify the Node.js version if needed
